Repository eventespresso/eea-recurring-events-manager, pull requests merged in 2020-10, with the labels that each got.

#29 Deployment to RC and barista sites
  .github/workflows/deploy-to-barista.yml
  .github/workflows/deploy-to-rc.yml
Labels: type:build-process 🔨, type:enhancement 🎉

#28 Add Recurrence Table and JOIN with Datetimes
  .travis.yml
  assets/ee-rem-dates-list.css
  composer.json
  domain/Domain.php
  domain/RecurringEventsManager.php
  domain/entities/admin/GraphQLData/Recurrences.php
  domain/entities/db_class_extensions/EEE_Recurrence_Datetime.class_ext.php
  domain/entities/db_classes/EE_Recurrence.class.php
  domain/entities/db_model_extensions/EEME_Recurrence_Datetime.model_ext.php
  domain/entities/db_models/EEM_Recurrence.model.php
  domain/services/admin/RecurringEventsTemplateSettingsFormHandler.php
  domain/services/data_migration_scripts/EE_DMS_Recurring_Events_1_0_0.dms.php
  domain/services/graphql/RegisterSchema.php
  domain/services/graphql/connection_resolvers/RecurrenceConnectionResolver.php
  domain/services/graphql/connections/RootQueryRecurrencesConnection.php
  domain/services/graphql/data/domains/EspressoEditor.php
  domain/services/graphql/data/loaders/RecurrenceLoader.php
  domain/services/graphql/data/mutations/RecurrenceMutation.php
  domain/services/graphql/mutators/RecurrenceCreate.php
  domain/services/graphql/mutators/RecurrenceDelete.php
  domain/services/graphql/mutators/RecurrenceUpdate.php
  domain/services/graphql/types/Recurrence.php
  domain/services/modules/EED_Recurring_Events.module.php
  eea-recurring-events-bootstrap.php
  eea-recurring-events-manager.php
  tests/bin/setup-addon-tests.sh
  tests/bootstrap.php
  tests/phpunit.xml
  tests/testcases/domain/services/modules/EED_Recurring_Events_Test.php
Labels: category:core-plugin, status:review, type:feature-request 🙏

#33 Fix DMS
  .travis.yml
  domain/services/data_migration_scripts/EE_DMS_Recurring_Events_1_0_0.dms.php
Labels: category:models-and-data-infrastructure, status:review, type:bug 🐞

#34 Add REM Routes and DOM Data closes #30
  composer.json
  domain/RecurringEventsManager.php
  domain/entities/admin/GraphQLData/Recurrences.php
  domain/entities/routing/EspressoEventEditor.php
  domain/entities/routing/EventTemplatesAdmin.php
  domain/entities/routing/FrontendRequests.php
  domain/entities/routing/GQLRequests.php
  domain/entities/routing/RemAdminRoute.php
  domain/entities/routing/RemEditorData.php
  domain/services/dependencies/EventEditorDependencyHandler.php
  domain/services/graphql/RegisterResources.php
  domain/services/graphql/RegisterSchema.php
  domain/services/modules/EED_Recurring_Events.module.php
  domain/ui/ee-rem-dates-list.css
  tests/testcases/domain/entities/config/RecurringEventsConfigTest.php
  tests/testcases/domain/services/modules/EED_Recurring_Events_Test.php
Labels: category:core-plugin, status:review, type:enhancement 🎉

#35 Ensure WP GraphQL is Loaded Before Registering Add-on
  eea-recurring-events-bootstrap.php
Labels: category:activation-installation-and-migration, status:review, type:enhancement 🎉

#36 Fix Dates List Scaling and Styles
  domain/entities/routing/FrontendRequests.php
  domain/ui/ee-rem-dates-list.css
Labels: REM, category:frontend-ui-&-ux, status:review, type:enhancement 🎉
